[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  [functions."check-reminders"]
  schedule = "0 * * * *"
  [functions."servicem8-check-new-jobs"]
  schedule = "*/15 * * * *"
  [functions."check-mileage-reminders"]
  schedule = "*/15 * * * *"
